### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by MUXIANGRU** [bagh2178/SG-Nav#1]
Thanks for open-sourcing your nice work!
I curretly try to test the code, but I found some version conflict about habitat-lab.When I load "challenge_objectnav2021.local.rgbd.yaml", it return "omegaconf.errors.ConfigAttributeError: Key 'habitat' is not in struct".:
  File "/home/ubuntu/SG-Nav/SG_Nav.py", line 1386, in <module>
    main()
  File "/home/ubuntu/SG-Nav/SG_Nav.py", line 1367, in main
    config = habitat.get_config(config_paths)
It seems the param.yaml is different from the habitat yaml, so I wonder which version of habitat you using.

Thanks!

**Comment by bagh2178** [comment]
Thank you very much for your attention. The versions are habitat-sim==0.2.4 habitat-lab==0.2.1.

**Comment by jinchenyu** [comment]
> Thank you very much for your attention. The versions are habitat-sim==0.2.4 habitat-lab==0.2.1.

I try the habitat-sim==0.2.4 habitat-lab==0.2.1.
It look like not compatible

"""bash
python SG_Nav.py --evaluation local --reasoning both
No module named 'habitat_sim.robots'
No module named 'habitat_sim.robots'
No module named 'habitat_sim.robots'
No module named 'habitat_sim.robots'
Traceback (most recent call last):
  File "/workspace/SG-Nav/SG_Nav.py", line 23, in <module>
    import habitat
  File "/workspace/SG-Nav/habitat-lab/habitat/__init__.py", line 9, in <module>
    from habitat.core.benchmark import Benchmark
  File "/workspace/SG-Nav/habitat-lab/habitat/core/benchmark.py", line 18, in <module>
    from habitat.core.env import Env
  File "/workspace/SG-Nav/habitat-lab/habitat/core/env.py", line 22, in <module>
    from habitat.tasks import make_task
  File "/workspace/SG-Nav/habitat-lab/habitat/tasks/__init__.py", line 7, in <module>
    from habitat.tasks.registration import make_task  # noqa: F401
  File "/workspace/SG-Nav/habitat-lab/habitat/tasks/registration.py", line 28, in <module>
    _try_register_rearrange_task()
  File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/__init__.py", line 33, in _try_register_rearrange_task
    import habitat.tasks.rearrange.actions
  File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/actions.py", line 15, in <module>
    from habitat.tasks.rearrange.rearrange_sim import RearrangeSim
  File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 33, in <module>
    from habitat_sim.robots import FetchRobot
ModuleNotFoundError: No module named 'habitat_sim.robots'
"""

**Comment by MUXIANGRU** [comment]
> > Thank you very much for your attention. The versions are habitat-sim==0.2.4 habitat-lab==0.2.1.
> 
> I try the habitat-sim==0.2.4 habitat-lab==0.2.1. It look like not compatible
> 
> """ python SG_Nav.py --evaluation local --reasoning both No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' Traceback (most recent call last): File "/workspace/SG-Nav/SG_Nav.py", line 23, in import habitat File "/workspace/SG-Nav/habitat-lab/habitat/**init**.py", line 9, in from habitat.core.benchmark import Benchmark File "/workspace/SG-Nav/habitat-lab/habitat/core/benchmark.py", line 18, in from habitat.core.env import Env File "/workspace/SG-Nav/habitat-lab/habitat/core/env.py", line 22, in from habitat.tasks import make_task File "/workspace/SG-Nav/habitat-lab/habitat/tasks/**init**.py", line 7, in from habitat.tasks.registration import make_task # noqa: F401 File "/workspace/SG-Nav/habitat-lab/habitat/tasks/registration.py", line 28, in _try_register_rearrange_task() File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/**init**.py", line 33, in _try_register_rearrange_task import habitat.tasks.rearrange.actions File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/actions.py", line 15, in from habitat.tasks.rearrange.rearrange_sim import RearrangeSim File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 33, in from habitat_sim.robots import FetchRobot ModuleNotFoundError: No module named 'habitat_sim.robots' """

So am I. @bagh2178 , would you like to check the version ? Thank you very much!

**Comment by jinchenyu** [comment]
> > > Thank you very much for your attention. The versions are habitat-sim==0.2.4 habitat-lab==0.2.1.
> > 
> > 
> > I try the habitat-sim==0.2.4 habitat-lab==0.2.1. It look like not compatible
> > """ python SG_Nav.py --evaluation local --reasoning both No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' No module named 'habitat_sim.robots' Traceback (most recent call last): File "/workspace/SG-Nav/SG_Nav.py", line 23, in import habitat File "/workspace/SG-Nav/habitat-lab/habitat/**init**.py", line 9, in from habitat.core.benchmark import Benchmark File "/workspace/SG-Nav/habitat-lab/habitat/core/benchmark.py", line 18, in from habitat.core.env import Env File "/workspace/SG-Nav/habitat-lab/habitat/core/env.py", line 22, in from habitat.tasks import make_task File "/workspace/SG-Nav/habitat-lab/habitat/tasks/**init**.py", line 7, in from habitat.tasks.registration import make_task # noqa: F401 File "/workspace/SG-Nav/habitat-lab/habitat/tasks/registration.py", line 28, in _try_register_rearrange_task() File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/**init**.py", line 33, in _try_register_rearrange_task import habitat.tasks.rearrange.actions File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/actions.py", line 15, in from habitat.tasks.rearrange.rearrange_sim import RearrangeSim File "/workspace/SG-Nav/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 33, in from habitat_sim.robots import FetchRobot ModuleNotFoundError: No module named 'habitat_sim.robots' """
> 
> So am I. @bagh2178 , would you like to check the version ? Thank you very much!

I try the habitat-sim==0.2.1, habitat-lab==0.2.1 or the habitat-sim==0.2.2, habitat-lab==0.2.2, it's work
Config format is change in v0.2.3

**Comment by MUXIANGRU** [comment]
> I try the habitat-sim==0.2.1, habitat-lab==0.2.1 or the habitat-sim==0.2.2, habitat-lab==0.2.2, it's work
> Config format is change in v0.2.3

Thank you for your help! I will try it.

**Comment by jinchenyu** [comment]
> > I try the habitat-sim==0.2.1, habitat-lab==0.2.1 or the habitat-sim==0.2.2, habitat-lab==0.2.2, it's work
> > Config format is change in v0.2.3
> 
> Thank you for your help! I will try it.

直接中文了，我跑他RandomAgent没问题，SG_Nav的BUG有点多，另一个issue有提到，不知道您这边能复现吗

**Comment by bagh2178** [comment]
For habitat-lab, you can try to install the version in our code if the official version is not compatible. The installation command is ``pip install -e habitat-lab``. Any other questions are welcome.
